# Generated by Django 2.1.5 on 2019-02-19 13:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hashtrend_app', '0002_auto_20190125_1622'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SavedPhotos',
            new_name='UserLog',
        ),
    ]
